### ISSUE TITLE
lxml fails to install on pypy travis test branch

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#1006]
See [these lines](https://travis-ci.org/ParmEd/ParmEd/jobs/418852296#L691-L716):
```
    building 'lxml.etree' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    creating build/temp.linux-x86_64-2.7/src/lxml
    cc -O2 -fPIC -Wimplicit -DCYTHON_CLINE_IN_TRACEBACK=0 -I/usr/include/libxml2 -Isrc -Isrc/lxml/includes -I/home/travis/.pyenv/versions/pypy-4.0.1/include -c src/lxml/etree.c -o build/temp.linux-x86_64-2.7/src/lxml/etree.o -w
    src/lxml/etree.c:1337:3: error: unknown type name ‘PyBaseExceptionObject’
       PyBaseExceptionObject __pyx_base;
       ^
    Compile failed: command 'cc' failed with exit status 1
    creating tmp
    cc -O2 -fPIC -Wimplicit -I/usr/include/libxml2 -I/usr/include/libxml2 -c /tmp/xmlXPathInitXqmymR.c -o tmp/xmlXPathInitXqmymR.o
    /tmp/xmlXPathInitXqmymR.c:2:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
     main (int argc, char **argv) {
     ^
    cc tmp/xmlXPathInitXqmymR.o -lxml2 -o a.out
    error: command 'cc' failed with exit status 1
    
    ----------------------------------------
    Command "/home/travis/.pyenv/versions/pypy-4.0.1/bin/pypy -c "import setuptools, tokenize;__file__='/tmp/pip-build-EbVafT/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-8G8xvb-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-EbVafT/lxml
```

**Comment by swails** [comment]
This is fixed in jchodera/ParmEd#9.

Most of the tests ran (and passed) anyway, so this wasn't a big deal.  But lxml was *known* not to work with pypy versions up to 4.0.1 (which is the very old version I had pinned the Travis build to).

Newer pypy versions are awesome.  I still have to check out their python 3.5 support, but they support wide swaths of the C-API now and "standard" numpy installs correctly out-of-the-box.  I'm thoroughly impressed.

**Comment by swails** [comment]
I'm going to close this issue, as it'll be fixed if you merge that PR.
