### ISSUE TITLE
@needs_openmm in all released versions not compatible with OpenMM 7.6

### ISSUE THREAD

**Issue by mattwthompson** [ParmEd/ParmEd#1185]
```
$ conda list | grep openmm
openmm                    7.6beta         py38h3e3929c_0_khronos    conda-forge/label/openmm_rc
$ python -c "import parmed as pmd; pmd.openmm.load_topology()"
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mwt/miniconda3/envs/openff-dev/lib/python3.8/site-packages/parmed/utils/decorators.py", line 30, in new_fcn
    raise ImportError('You must have at least OpenMM 6.3 installed')
ImportError: You must have at least OpenMM 6.3 installed
$ conda list | grep parmed
parmed                    3.4.1            py38ha048514_0    conda-forge
```

The same happens with the most [recent release](https://github.com/ParmEd/ParmEd/blob/3.4.1/parmed/utils/decorators.py) and what seems to be bundled with AmberTools (3.4.0), although it's been fixed on [master](https://github.com/ParmEd/ParmEd/blob/master/parmed/utils/decorators.py), perhaps inadvertently, since the offending line is `from simtk.openmm.app.internal import unitcell`, not `import simtk.openmm as mm`. This is separate from avoiding the deprecation warnings - as far as I can tell, anything using `@needs_openmm` will not work at all with any released versions of ParmEd and OpenMM 7.6 

You mention your mega-PR #1138  is targeted at 4.0 and presumably this should fix that - Is there a plan for that to be released?

**Comment by peastman** [comment]
> I don't suppose there's a way we can pin the OpenMM 7.6 conda package to note that it is incompatible with all versions of ParmEd < 4.0.0, but not install ParmEd as a dependency?

No idea.  That sort of conda magic is a bit beyond my experience.

It's not clear to me why it isn't working.  Here's the implementation of `@needs_openmm`:

https://github.com/ParmEd/ParmEd/blob/8ac72ce57402facb3972362e1ce53aad01490e5a/parmed/utils/decorators.py#L5-L20

`import simtk.openmm as mm` should work correctly in 7.6 (just printing a deprecation warning), so `HAS_OPENMM` ought to be true.

**Comment by peastman** [comment]
Something is very strange.  The stack trace above listed the line

```
  File "/Users/mwt/miniconda3/envs/openff-dev/lib/python3.8/site-packages/parmed/utils/decorators.py", line 30, in new_fcn
```

There isn't a line 30 in decorators.py!  The file is only 29 lines long.

**Comment by jchodera** [comment]
@peastman : @mattwthompson's [original comment](https://github.com/ParmEd/ParmEd/issues/1185#issue-950830864) notes that _all released versions_ have this issue, and he explicitly links the latest release:

https://github.com/ParmEd/ParmEd/blob/3.4.1/parmed/utils/decorators.py#L30

You made an observation about the latest `master`, which @mattwthompson's comment explicitly notes has been fixed.

While a new ParmEd release would work with OpenMM 7.6, the problem is that our release of OpenMM 7.6 breaks literally everything that depends on ParmEd at this point, which is going to cause a whole world of pain unless we figure out how to ensure that OpenMM 7.6 isn't used by anything that requires ParmEd via conda. 

If we can't solve this with some conda constraints, I think we will need to un-release OpenMM on conda-forge since so many of our toolchains require ParmEd.

**Comment by peastman** [comment]
If you simply put out a fixed ParmEd, I think that will mostly take care of it.  Conda is very aggressive about upgrading things.  If you do much of anything with an environment, even just removing a single package, it re-solves all dependencies and updates anything it can find to update.  If someone has ParmEd installed, and they update OpenMM, I believe conda will automatically update ParmEd at the same time even though it hasn't been told to.

**Comment by jchodera** [comment]
> If you simply put out a fixed ParmEd, I think that will mostly take care of it. Conda is very aggressive about upgrading things. If you do much of anything with an environment, even just removing a single package, it re-solves all dependencies and updates anything it can find to update. If someone has ParmEd installed, and they update OpenMM, I believe conda will automatically update ParmEd at the same time even though it hasn't been told to.

@peastman : We don't have a timeline for a fixed ParmEd, and that won't change the fact that none of the released ParmEd versions will work with OpenMM 7.6. 

I think we need a more coordinated release plan with ParmEd since this will be a significant issue for lots of packages in the OpenMM ecosystem. We should roll back and figure out how to solve this.

**Comment by jchodera** [comment]
@peastman : Also, I'll note [this issue has been posted since July 22](https://github.com/ParmEd/ParmEd/issues/1185#issue-950830864), so we _should_ had a significant amount of warning, except nobody seems to have noted this in an OpenMM issue to actually alert us of the problem until now.

**Comment by peastman** [comment]
I suggest putting out a patched ParmEd immediately.  Today.

> Also, I'll note this issue has been posted since July 22, so we should had a significant amount of warning

Agreed.  I'm not a ParmEd developer, so I can't speak to why no one fixed it.  But it isn't for lack of warning.

**Comment by jchodera** [comment]
> Agreed. I'm not a ParmEd developer, so I can't speak to why no one fixed it. But it isn't for lack of warning.

No, I'm saying _we've_ had since July 22 to address the issue, but we failed to do so. And now we've broken most of the OpenMM ecosystem---at least anything that uses ParmEd, which has 118K downloads as a stand-alone package and 304K downloads via ambertools.

This is a major issue for OpenMM---we are going to need to un-release 7.6 conda packages until we find a fix.

**Comment by peastman** [comment]
You could even make a ParmEd release that doesn't change any code at all, and simply adds the constraint `openmm < 7.6`.

> This is a major issue for OpenMM---we are going to need to un-release 7.6 conda packages until we find a fix.

I don't know if that's even possible, much less how one "unreleases" a release.  And I don't see why you're making such a big deal about this.  Just post a ParmEd release that changes one line in meta.yaml to indicate it doesn't work with OpenMM 7.6.  It's a very easy fix.  It will take minutes.

**Comment by jchodera** [comment]
> I don't know if that's even possible, much less how one "unreleases" a release. And I don't see why you're making such a big deal about this. 

The OpenMM 7.6 release breaks pretty much all of our own tools (including openmmforcefields), everything in the openforcefield ecosystem, and probably a lot of other things.

> Just post a ParmEd release that changes one line in meta.yaml to indicate it doesn't work with OpenMM 7.6. It's a very easy fix. It will take minutes.

How is that going to happen? 

We don't have permission to do this, and everything will remain broken until it happens. I'm not sure who is a maintainer of ParmEd beyond @swails, and he's no longer actively maintaining ParmEd, so his response time has been weeks or longer. I know @jaimergp is a maintainer of the [conda-forge feedstock](https://github.com/conda-forge/parmed-feedstock/blob/master/recipe/meta.yaml#L64-L69) as well, so perhaps we could get his attention to help us out in the meantime.

**Comment by swails** [comment]
I can cut a new release.

**Comment by jchodera** [comment]
@swails : Enormous thanks, and apologies for the unplanned panic.

**Comment by swails** [comment]
No worries.  In retrospect maybe would've been a good excuse to jump to OMM 8.0, but I guess that ship's sailed.

**Comment by jchodera** [comment]
> No worries. In retrospect maybe would've been a good excuse to jump to OMM 8.0, but I guess that ship's sailed.

Can't say I didn't try: https://github.com/openmm/openmm/issues/3130#issuecomment-851611598

**Comment by peastman** [comment]
Thanks!

**Comment by jchodera** [comment]
Once @swails merges this PR, hopefully we can close this issue:
https://github.com/conda-forge/parmed-feedstock/pull/15

**Comment by mattwthompson** [comment]
I'm not sure this is resolved? I updated everything to what I think are the most recent versions (AmberTools 21.7, ParmEd 3.4.2, and OpenMM 7.6)

```python3
>>> import parmed as pmd
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
>>> import openmm
>>> pmd.__version__
'3.4.2'
>>> openmm.__version__
'7.6'
>>> pmd.openmm.load_topology()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mwt/miniconda3/envs/openff-dev/lib/python3.9/site-packages/parmed/utils/decorators.py", line 30, in new_fcn
    raise ImportError('You must have at least OpenMM 6.3 installed')
ImportError: You must have at least OpenMM 6.3 installed
```

**Comment by jchodera** [comment]
cc @swails

**Comment by mattwthompson** [comment]
The file in my `site-packages` appears to be the same as what's tagged to 3.4.2: https://github.com/ParmEd/ParmEd/blob/3.4.2/parmed/utils/decorators.py

But that's the same as what's in the version in 3.4.1: https://github.com/ParmEd/ParmEd/blob/3.4.1/parmed/utils/decorators.py

**The fixes are in the master branch** [here](https://github.com/ParmEd/ParmEd/blob/master/parmed/utils/decorators.py) or tagged to the most recent commit [here](https://github.com/ParmEd/ParmEd/blob/8ac72ce57402facb3972362e1ce53aad01490e5a/parmed/utils/decorators.py), since the link with `/master/` it is not permanent.

**Comment by jaimergp** [comment]
It looks like the update only covered one of the possible imports:

https://github.com/ParmEd/ParmEd/compare/3.4.1...3.4.2

**Comment by mattwthompson** [comment]
I'm confused why my links are funky - copying the 3.4.2 into my browser opens up what I'd expect, and I can pull the tag locally?

```
$ git fetch --all
$ git tag | grep 3.4
3.4.0
3.4.1
3.4.2
```

I checked the tarball that's pulled into the feedstock and nothing is out of line (SHA matches, file is the same as what got installed into my `site-packages`)

**Comment by jaimergp** [comment]
I think the package itself is ok; they problem is that the 3.4.2 tag [does not contain](https://github.com/ParmEd/ParmEd/blob/master/parmed/utils/decorators.py#L6) the decorator updates.

**Comment by mattwthompson** [comment]
I'm also finding zero faults with conda, forge, or anything related to packaging. Originally I had noted  the same thing, that the `master` branch has the fix and that a release including it (4.0?) would fix it.

**Comment by peastman** [comment]
@mattwthompson how about if you create a PR to parmed-feedstock to do a new build with the revision you think is correct?  @swails can look it over and merge it if everything looks ok.

**Comment by mattwthompson** [comment]
Here is what that looks like, although I had to make it from a fork (bad practice) since I cannot create ParmEd releases.

https://github.com/conda-forge/parmed-feedstock/pull/17

**Comment by peastman** [comment]
I posted a different PR at https://github.com/conda-forge/parmed-feedstock/pull/18.  This one does nothing except increment the build number and add the dependency `openmm <7.6`.  @swails if getting a proper fix out is going to take too long, can you merge this one in the mean time?  It will address the immediate breakage.

**Comment by jchodera** [comment]
> I posted a different PR at conda-forge/parmed-feedstock#18. This one does nothing except increment the build number and add the dependency openmm <7.6. @swails if getting a proper fix out is going to take too long, can you merge this one in the mean time? It will address the immediate breakage.

That won't work, since the previous broken build numbers which do not have that constraint would be installed instead, but will not work with openmm 7.6.

**Comment by sroet** [comment]
> That won't work, since the previous broken build numbers which do not have that constraint would be installed instead, but will not work with openmm 7.6.

Just want to make sure you know about the [ability to retro-actively fix repodata on conda-forge](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock) (such as had to be done [here](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/121) for mdtraj 

If you want I can create a similar PR to pin previous build of parmed to openmm<7.6

**Comment by peastman** [comment]
Thanks!

**Comment by sroet** [comment]
> Sounds good! 3.4.3 will fix support for OpenMM 7.6.

With [this PR](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/166) merged, all conda-forge builds of `parmed<3.4.3` should now (after conda-forge rebuilds) have a constraint `openmm <7.6`

**Comment by mattwthompson** [comment]
3.4.3 works for me locally, with minimal testing. But at least the major API route can be loaded.

I installed with 
```
$ pip install git+https://github.com/parmed/parmed.git@3.4.3
```

And quick check
```
>>> import parmed as pmd
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
>>> import openmm
>>> pmd.openmm.load_topology()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mwt/miniconda3/envs/openff-system/lib/python3.9/site-packages/parmed/utils/decorators.py", line 22, in new_fcn
    return fcn(*args, **kwargs)
TypeError: load_topology() missing 1 required positional argument: 'topology'
```

As a separate matter, it looks like fresh installs are working as expected thanks to @sroet's patch:


```
$ mamba install ambertools openmm -c conda-forge -q
  Package       Version  Build                   Channel                  Size
────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────

  + ambertools     21.7  py39h47b4d88_0          conda-forge/osx-64     Cached
  + openmm        7.5.1  py39h8d72adf_1_khronos  conda-forge/osx-64       9 MB
  + parmed        3.4.2  py39h9fcab8e_0          conda-forge/osx-64     Cached

  Summary:

  Install: 3 packages

  Total download: 9 MB

────────────────────────────────────────────────────────────────────────────────

Confirm changes: [Y/n]
```


Same behavior if I ask it for ParmEd + OpenMM, AmberTools + OpenMM, or just the OpenFF Toolkit.

**Comment by jaimergp** [comment]
The ParmEd 3.4.3 packages should be out now too!

**Comment by swails** [comment]
This should be resolved by the new pins on ParmEd <3.4.3 and the release of ParmEd 3.4.3.

Thanks everyone!
