### ISSUE TITLE
ala5

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#446]
I try to follow your example here with openmm but can not find ala5 in test files.
http://parmed.github.io/ParmEd/html/omm_amber.html
Can you either
* change ala5 to ala_ala_ala
* or add ala5 to your test cases?

Just want to make sure that if I copy and paste your example, it will work.

**Comment by hainm** [comment]
one more point:

I was suggesting to use ipython directive to rerun your doc code to make sure that it works. The above example does not work.

```python
from parmed import unit
```

should be 
```python
from parmed import unit as u
```

**Comment by hainm** [comment]
after updating 'unit as u', change CUDA to CPU and get rid of few things, I still got error:

```bash
$ python  test_cpu_openmm_parmed.py
Loading Amber files...
Creating OpenMM System
Minimizing energy
Traceback (most recent call last):
  File "test_cpu_openmm_parmed.py", line 55, in <module>
    uses_pbc=False, crds=True)
  File "/mnt/raidc2/haichit/anaconda3/lib/python3.4/site-packages/parmed/utils/decorators.py", line 30, in new_fcn
    return fcn(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'uses_pbc'
Exception ignored in: <bound method NetCDFReporter.__del__ of <parmed.openmm.reporters.NetCDFReporter object at 0x7fc8bce39e80>>
Traceback (most recent call last):
  File "/mnt/raidc2/haichit/anaconda3/lib/python3.4/site-packages/parmed/openmm/reporters.py", line 386, in __del__
    if self._out is not None:
AttributeError: 'NetCDFReporter' object has no attribute '_out'
```

any idea why? thanks

**Comment by swails** [comment]
This example should be fixed.  Note that the website you quoted stated that these files are in `examples/amber`, which they are.  If you run this example now, it should work fine (it worked on my computer with both Python 2.7 and 3.4).

I also fixed the destructor exception you reported (although the *real* error was passing an unsupported keyword `uses_pbc`, which has been removed from the example on the website.

Thanks for the report.

**Comment by swails** [comment]
The real example script, `ParmEd/examples/amber/simulate_amber_gb.py`, works fine.  I should probably have the docs pull the example from this script (it is intended to be the same) -- I'm just not sure of an easy way to do that outside of adding it to `conf.py` (which already generates `parmed.rst`).

**Comment by hainm** [comment]
Yeah, sorry not read the doc carefully.

**Comment by hainm** [comment]
I dont have gpu so I need to change to CPU and delete gpu stuff to make your example work.

What is about using CPU for example and add gpu in comments? Not so many people have gpu and normally need to submit to cluster to run.

**Comment by hainm** [comment]
Per running example with doc, you can use ipython or notebook directive. In ling term, i think this way will save you lot of time. 

http://amber-md.github.io/pytraj/doc/build/html/_sources/tips.txt

http://amber-md.github.io/pytraj/doc/build/html/tips.html

**Comment by hainm** [comment]
ling term = long term
